### ISSUE TITLE
npm install fails on Mojave

### ISSUE THREAD

**Issue by Dirk-** [tugrul/cryptian#1]
I tried to install cryptian on macOS 10.14.5 with an up-to-date version of `brew` and `npm` installed. `npm install` fails with the output below. Any advice?

Thanks a lot,
Dirk

```
MacBook-Pro:cryptian dirk$ npm install

> fsevents@1.2.9 install /Users/dirk/Projekte/Uebung/cryptian/node_modules/fsevents
> node install

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[fsevents] Success: "/Users/dirk/Projekte/Uebung/cryptian/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> core-js@3.1.4 postinstall /Users/dirk/Projekte/Uebung/cryptian/node_modules/core-js
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js-pure@3.1.4 postinstall /Users/dirk/Projekte/Uebung/cryptian/node_modules/core-js-pure
> node scripts/postinstall || echo "ignore"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> cryptian@0.0.2 install /Users/dirk/Projekte/Uebung/cryptian
> node-gyp rebuild

  CXX(target) Release/obj.target/cryptian/addon/lib/algorithm/threeway.o
  CXX(target) Release/obj.target/cryptian/addon/lib/algorithm/arcfour.o
  CXX(target) Release/obj.target/cryptian/addon/lib/algorithm/blowfish.o
  CXX(target) Release/obj.target/cryptian/addon/lib/algorithm/cast-128.o
  CXX(target) Release/obj.target/cryptian/addon/lib/algorithm/cast-256.o
  CXX(target) Release/obj.target/cryptian/addon/lib/algorithm/des.o
  CXX(target) Release/obj.target/cryptian/addon/lib/algorithm/enigma.o
  CXX(target) Release/obj.target/cryptian/addon/lib/algorithm/gost.o
  CXX(target) Release/obj.target/cryptian/addon/lib/algorithm/loki97.o
  CXX(target) Release/obj.target/cryptian/addon/lib/algorithm/rc2.o
  CXX(target) Release/obj.target/cryptian/addon/lib/algorithm/rijndael.o
  CXX(target) Release/obj.target/cryptian/addon/lib/algorithm/safer.o
  CXX(target) Release/obj.target/cryptian/addon/lib/algorithm/saferplus.o
  CXX(target) Release/obj.target/cryptian/addon/lib/algorithm/tripledes.o
  CXX(target) Release/obj.target/cryptian/addon/lib/algorithm/wake.o
  CXX(target) Release/obj.target/cryptian/addon/lib/algorithm/xtea.o
  CXX(target) Release/obj.target/cryptian/addon/lib/algorithm/dummy.o
  CXX(target) Release/obj.target/cryptian/addon/lib/mode/cbc.o
  CXX(target) Release/obj.target/cryptian/addon/lib/mode/cfb.o
  CXX(target) Release/obj.target/cryptian/addon/lib/mode/ctr.o
  CXX(target) Release/obj.target/cryptian/addon/lib/mode/ecb.o
  CXX(target) Release/obj.target/cryptian/addon/lib/mode/ncfb.o
  CXX(target) Release/obj.target/cryptian/addon/lib/mode/nofb.o
  CXX(target) Release/obj.target/cryptian/addon/lib/mode/ofb.o
  CXX(target) Release/obj.target/cryptian/addon/src/node/cryptian.o
In file included from ../addon/src/node/cryptian.cc:2:
In file included from ../addon/src/node/cryptian.h:3:
../addon/src/node/algorithm.h:14:12: error: no template named 'Handle'
    static Handle<FunctionTemplate> getFunctionTemplate(std::string functionName) {
           ^
../addon/src/node/algorithm.h:42:46: error: no template named 'Handle'
    static std::vector<char> convertToVector(Handle<Value> val) {
                                             ^
../addon/src/node/algorithm.h:20:44: error: too few arguments to function call, single argument 'context' was not specified
        constructor.Reset(tpl->GetFunction());
                          ~~~~~~~~~~~~~~~~ ^
/Users/dirk/.node-gyp/12.5.0/include/node/v8.h:5948:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/dirk/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../addon/src/node/cryptian.cc:2:
In file included from ../addon/src/node/cryptian.h:3:
../addon/src/node/algorithm.h:22:16: error: no viable conversion from returned value of type 'Local<v8::FunctionTemplate>' to function return type 'int'
        return tpl;
               ^~~
../addon/src/node/algorithm.h:90:20: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
            array->Set(i, Nan::New<Number>(keySizes[i]));
                   ^
/Users/dirk/.node-gyp/12.5.0/include/node/v8.h:3367:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON("Use maybe version",
  ^
/Users/dirk/.node-gyp/12.5.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATE_SOON'
  declarator __attribute__((deprecated(message)))
                            ^
In file included from ../addon/src/node/cryptian.cc:2:
In file included from ../addon/src/node/cryptian.h:3:
../addon/src/node/algorithm.h:159:86: error: too few arguments to function call, expected 2, have 1
        container->algorithm->setEndianCompat(info[0]->Equals(Nan::New<Boolean>(true)));
                                              ~~~~~~~~~~~~~~~                        ^
/Users/dirk/.node-gyp/12.5.0/include/node/v8.h:2572:3: note: 'Equals' declared here
  V8_WARN_UNUSED_RESULT Maybe<bool> Equals(Local<Context> context,
  ^
/Users/dirk/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../addon/src/node/cryptian.cc:2:
In file included from ../addon/src/node/cryptian.h:3:
../addon/src/node/algorithm.h:171:12: error: no template named 'Handle'
    static Handle<FunctionTemplate> getFunctionTemplate(std::string functionName, Local<FunctionTemplate> parent) {
           ^
../addon/src/node/algorithm.h:193:62: error: too few arguments to function call, single argument 'context' was not specified
        AlgorithmBase<T>::constructor.Reset(tpl->GetFunction());
                                            ~~~~~~~~~~~~~~~~ ^
/Users/dirk/.node-gyp/12.5.0/include/node/v8.h:5948:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/dirk/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../addon/src/node/cryptian.cc:2:
In file included from ../addon/src/node/cryptian.h:3:
../addon/src/node/algorithm.h:195:16: error: no viable conversion from returned value of type 'Local<v8::FunctionTemplate>' to function return type 'int'
        return tpl;
               ^~~
../addon/src/node/algorithm.h:229:12: error: no template named 'Handle'
    static Handle<FunctionTemplate> getFunctionTemplate(std::string functionName, Local<FunctionTemplate> parent) {
           ^
../addon/src/node/algorithm.h:251:62: error: too few arguments to function call, single argument 'context' was not specified
        AlgorithmBase<T>::constructor.Reset(tpl->GetFunction());
                                            ~~~~~~~~~~~~~~~~ ^
/Users/dirk/.node-gyp/12.5.0/include/node/v8.h:5948:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/dirk/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../addon/src/node/cryptian.cc:2:
In file included from ../addon/src/node/cryptian.h:3:
../addon/src/node/algorithm.h:253:16: error: no viable conversion from returned value of type 'Local<v8::FunctionTemplate>' to function return type 'int'
        return tpl;
               ^~~
In file included from ../addon/src/node/cryptian.cc:2:
In file included from ../addon/src/node/cryptian.h:6:
../addon/src/node/mode.h:23:12: error: no template named 'Handle'
    static Handle<FunctionTemplate> getFunctionTemplate() {
           ^
../addon/src/node/mode.h:28:44: error: too few arguments to function call, single argument 'context' was not specified
        constructor.Reset(tpl->GetFunction());
                          ~~~~~~~~~~~~~~~~ ^
/Users/dirk/.node-gyp/12.5.0/include/node/v8.h:5948:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/dirk/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
In file included from ../addon/src/node/cryptian.cc:2:
In file included from ../addon/src/node/cryptian.h:6:
../addon/src/node/mode.h:30:16: error: no viable conversion from returned value of type 'Local<v8::FunctionTemplate>' to function return type 'int'
        return tpl;
               ^~~
../addon/src/node/mode.h:55:46: error: no template named 'Handle'
    static std::vector<char> convertToVector(Handle<Value> val) {
                                             ^
../addon/src/node/mode.h:146:12: error: no template named 'Handle'
    static Handle<FunctionTemplate> getFunctionTemplate(std::string className, Local<FunctionTemplate> parent) {
           ^
../addon/src/node/mode.h:96:86: error: no matching member function for call to 'ToObject'
        node::ObjectWrap::Unwrap<AlgorithmBlock<algorithm::AlgorithmBlock>>(info[0]->ToObject());
                                                                            ~~~~~~~~~^~~~~~~~
/Users/dirk/.node-gyp/12.5.0/include/node/v8.h:2532:44: note: candidate function not viable: requires single argument 'context', but no arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/dirk/.node-gyp/12.5.0/include/node/v8.h:2546:31: note: candidate function not viable: requires single argument 'isolate', but no arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
In file included from ../addon/src/node/cryptian.cc:2:
In file included from ../addon/src/node/cryptian.h:6:
../addon/src/node/mode.h:98:53: error: no member named 'algorithm' in 'cryptian::AlgorithmBlock<cryptian::algorithm::AlgorithmBlock>'
        Mode<T>* container = new Mode<T>(algorithm->algorithm, convertToVector(info[1]));
                                         ~~~~~~~~~  ^
../addon/src/node/mode.h:157:44: error: too few arguments to function call, single argument 'context' was not specified
        constructor.Reset(tpl->GetFunction());
                          ~~~~~~~~~~~~~~~~ ^
/Users/dirk/.node-gyp/12.5.0/include/node/v8.h:5948:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/dirk/.node-gyp/12.5.0/include/node/v8config.h:351:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
1 warning and 20 errors generated.
make: *** [Release/obj.target/cryptian/addon/src/node/cryptian.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/12.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dirk/Projekte/Uebung/cryptian
gyp ERR! node -v v12.5.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cryptian@0.0.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cryptian@0.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dirk/.npm/_logs/2019-07-09T10_01_10_798Z-debug.log
MacBook-Pro:cryptian dirk$ 
```

**Comment by akhil-fit** [comment]
Facing the same issue, @Dirk- did you find any solution?

**Comment by tugrul** [comment]
It looks like general issue with node v12.

I'm going to try to upgrade nan.

**Comment by Dirk-** [comment]
@akhil-fit No, not yet.
@tugrul Thanks, that would be great!

**Comment by tugrul** [comment]
I published a new version. Can you test it?

**Comment by Dirk-** [comment]
`npm install` works. No errors or warnings. Teşekkür ederim!

**Comment by Dirk-** [comment]
@tugrul Is it incompatible to Windows now? You commented out that OS in `.travis.yml`.

**Comment by tugrul** [comment]
@Dirk- compatible to Windows but there is a problem on travis ci hard to solve. I can't install build dependencies for node v6 and node v7 on build server. 

I currently opt-out windows test on travis.

**Comment by Dirk-** [comment]
@tugrul Okay, I understand.
