### ISSUE TITLE
NPM install fails on node v13

### ISSUE THREAD

**Issue by pluma** [tugrul/cryptian#2]
```
<snip>
/home/pluma/.node-gyp/13.8.0/include/node/v8.h:3547:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3547 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/pluma/.node-gyp/13.8.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/pluma/.node-gyp/13.8.0/include/node/v8.h:3550:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3550 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/pluma/.node-gyp/13.8.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
../addon/src/node/cryptian.cc:81:114: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Function>)’
   81 |     exports->Set(Nan::New("AlgorithmStream").ToLocalChecked(), Nan::GetFunction(algorithmStream).ToLocalChecked());
      |                                                                                                                  ^
In file included from /home/pluma/.node-gyp/13.8.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../addon/src/node/algorithm.h:5,
                 from ../addon/src/node/cryptian.h:3,
                 from ../addon/src/node/cryptian.cc:2:
/home/pluma/.node-gyp/13.8.0/include/node/v8.h:3547:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3547 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/pluma/.node-gyp/13.8.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/pluma/.node-gyp/13.8.0/include/node/v8.h:3550:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3550 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/pluma/.node-gyp/13.8.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
../addon/src/node/cryptian.cc:83:96: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, v8::Local<v8::Function>)’
   83 |     exports->Set(Nan::New("Mode").ToLocalChecked(), Nan::GetFunction(modeBase).ToLocalChecked());
      |                                                                                                ^
In file included from /home/pluma/.node-gyp/13.8.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../addon/src/node/algorithm.h:5,
                 from ../addon/src/node/cryptian.h:3,
                 from ../addon/src/node/cryptian.cc:2:
/home/pluma/.node-gyp/13.8.0/include/node/v8.h:3547:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
 3547 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
      |                                     ^~~
/home/pluma/.node-gyp/13.8.0/include/node/v8.h:3547:37: note:   candidate expects 3 arguments, 2 provided
/home/pluma/.node-gyp/13.8.0/include/node/v8.h:3550:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
 3550 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
      |                                     ^~~
/home/pluma/.node-gyp/13.8.0/include/node/v8.h:3550:37: note:   candidate expects 3 arguments, 2 provided
In file included from ../../nan/nan.h:54,
                 from ../addon/src/node/algorithm.h:5,
                 from ../addon/src/node/cryptian.h:3,
                 from ../addon/src/node/cryptian.cc:2:
../addon/src/node/cryptian.cc: At global scope:
/home/pluma/.node-gyp/13.8.0/include/node/node.h:610:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
  610 |       (node::addon_register_func) (regfunc),                          \
      |                                           ^
/home/pluma/.node-gyp/13.8.0/include/node/node.h:644:3: note: in expansion of macro ‘NODE_MODULE_X’
  644 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
      |   ^~~~~~~~~~~~~
../addon/src/node/cryptian.cc:86:1: note: in expansion of macro ‘NODE_MODULE’
   86 | NODE_MODULE(cryptian, Init)
      | ^~~~~~~~~~~
In file included from /home/pluma/.node-gyp/13.8.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from ../addon/src/node/algorithm.h:5,
                 from ../addon/src/node/cryptian.h:3,
                 from ../addon/src/node/cryptian.cc:2:
/home/pluma/.node-gyp/13.8.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/home/pluma/.node-gyp/13.8.0/include/node/node_object_wrap.h:85:78:   required from here
/home/pluma/.node-gyp/13.8.0/include/node/v8.h:10400:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
10400 |                reinterpret_cast<Callback>(callback), type);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/pluma/.node-gyp/13.8.0/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/home/pluma/.node-gyp/13.8.0/include/node/v8.h:10400:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
cryptian.target.mk:139: recipe for target 'Release/obj.target/cryptian/addon/src/node/cryptian.o' failed
make: *** [Release/obj.target/cryptian/addon/src/node/cryptian.o] Error 1
make: Leaving directory '/home/pluma/temp/node_modules/cryptian/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/pluma/temp/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.84-microsoft-standard
gyp ERR! command "/usr/bin/node" "/home/pluma/temp/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/pluma/temp/node_modules/cryptian
gyp ERR! node -v v13.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

**Comment by tugrul** [comment]
Thank you for reporting. 

I published a version to NPM.
