### ISSUE TITLE
Apple M1 Error `cryptian.node: mach-o, but wrong architecture`

### ISSUE THREAD

**Issue by irishkungfu** [tugrul/cryptian#8]
We are attempting to setup our dev environment to work on Apple's new M1 platform and we've hit a snag. `cryptian.node` does seem to be compiling to the correct platform. We have verified that our python build is 3.8.1 and using arm64 and clang is also using arm64.  We've looked at countless threads in other libraries in which users have similar issues, but we can't seem to resolve this.  Do you have any thoughts on what could be causing this issue?  
```
/Users/username/Documents/Virtuance/virtuance-services/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: dlopen(/Users/username/Documents/Virtuance/virtuance-services/node_modules/cryptian/build/Release/cryptian.node, 1): no suitable image found.  Did find:
        /Users/username/Documents/Virtuance/virtuance-services/node_modules/cryptian/build/Release/cryptian.node: mach-o, but wrong architecture
        /Users/username/Documents/Virtuance/virtuance-services/node_modules/cryptian/build/Release/cryptian.node: mach-o, but wrong architecture
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:909:18)
    at Module.load (internal/modules/cjs/loader.js:731:32)
    at Function.Module._load (internal/modules/cjs/loader.js:644:12)
    at Module.require (internal/modules/cjs/loader.js:771:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at bindings (/Users/username/Documents/Virtuance/virtuance-services/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/username/Documents/Virtuance/virtuance-services/node_modules/cryptian/lib/index-back.js:3:52)
    at Module._compile (internal/modules/cjs/loader.js:868:30)
    at Module._compile (/Users/username/Documents/Virtuance/virtuance-services/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:879:10)
```

**Comment by tugrul** [comment]
I see some solutions on different bug reports. One of the solutions is updating `node-gyp` on your machine. 

I can't test this problem to fix because I don't have an M1 machine. I already updated `nan` dependency and maybe the problem may have been solved by natural ways.
